# --------------------------------------------------------------------------- #
# A Snakemake workflow for the detection of small nucleotide and structural   #
# variants in bacterial ONT long-read sequencing data.                        #
#                                                                             #
# Author: Thomas F. Wulff                                                     #
# Date: 2024-01-15                                                            #
# License: Free for non-commercial use (see LICENSE).                         #
#          For all 3rd party tools separate licenses may apply.               #
# --------------------------------------------------------------------------- #


# --------------------------------------------------------------------------- #
# Set paths and parameters for workflow                                       #
# --------------------------------------------------------------------------- #
configfile: "config/config.yml"


rootdir = os.getcwd()
indir = os.path.join(rootdir, config["indir"])
outdir = os.path.join(rootdir, config["outdir"])


# --------------------------------------------------------------------------- #
# Retrieve sample information from config.yml                                 #
# --------------------------------------------------------------------------- #
include: "rules/common.smk"


SAMPLEINFO = read_sample_sheet()
SAMPLES = list(SAMPLEINFO["sample"])
GENOMES = list_reference_genomes()


wildcard_constraints:
    sample="[^/|.]*",


# --------------------------------------------------------------------------- #
# Include sub-workflows                                                       #
# --------------------------------------------------------------------------- #
include: "rules/mapping.smk"
include: "rules/small_nucleotide_variants.smk"
include: "rules/structural_variants.smk"
include: "rules/variant_filtering.smk"
include: "rules/quality_control.smk"
include: "rules/report.smk"
include: "rules/annotation.smk"


rule all:
    input:
        generate_results,

rule test:
    input:
        # expand(os.path.join(outdir, "SNV/NanoCaller/{sample}.vcf"), sample=SAMPLES),
        # expand(os.path.join(outdir, "SNV/NanoCaller/{sample}.filtered.vcf"), sample=SAMPLES),
        # expand(os.path.join(outdir, "variant_reports/{sample}/{sample}.NanoCaller.vcf"), sample=SAMPLES),
        # expand(os.path.join(outdir, "variant_reports/{sample}/{sample}.{tool}.annotated.gd"), sample=SAMPLES, tool=["clair3", "medaka", "NanoCaller", "cutesv", "sniffles2"]),
        # expand(os.path.join(outdir, "variant_reports/comparison.{type}"), type=["html", 'tsv']),
        # expand(os.path.join(outdir, "breseq/{sample}/data/annotated.gd"), sample=SAMPLES),
        # expand(os.path.join(outdir, "variant_reports/MEK560/MEK560_overview.html")),
        # expand(os.path.join(outdir, "SNV/DeepVariant/{sample}.vcf"), sample=SAMPLES),
        # os.path.join(outdir, "inputs", "CP012712.1.fa.fai"),
        os.path.join(outdir, "inputs", "CP012712.1-THL-Tle-Cac.fa.fai"),